### ISSUE TITLE
Thx, API doubt

### ISSUE THREAD

**Issue by amrrs** [tylerburleigh/nutritionR#1]
Hey Thanks for making this!

Just wondering this API call limit mentioned here https://www.nutritionix.com/business/api means, only two users can use this package in a month?

**Comment by tylerburleigh** [comment]
Yes, but I don't know how that applies to "development mode" which is the mode this package will be in when sending requests.

From the [API docs section on authentication](https://docs.google.com/document/d/1_q-K-ObMTZvO0qUEAxROrN3bwMujwAN25sLHwJzliK0/edit#bookmark=id.bziwdnqu5ud1), it sounds like Nutritionix is using the `x-remote-user-id` header to determine the number of users on a key.

However, this is not a required header parameter and I haven't added it to the `nutritionix_lookup()` function. I believe when it's not specified it defaults to a value of 0 and is considered to be "in development mode", but I'm not sure what that means for request limits.

If you get a chance to test the limits, please report back!
